assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

branches:
  only:
    - master
    - release

build_script:
  - cmd: build.cmd

test_script:
  - cmd: test.cmd